import { Item, ProdutoResponse, Venda } from '../types';
import { formatToCurrency } from './currency';

function getValorUnitario(raw: any): string {
    return String(raw?.valor_unitario ?? raw?.valor_venda ?? raw?.valor ?? 0);
}

function getUnidade(raw: any): string {
    return String(raw?.unidade ?? raw?.unidade_venda ?? 'UN');
}

function getCodigoBarras(raw: any): string | null {
    return (raw?.codigo_barras ?? raw?.codBarras ?? null) as any;
}

function getNcm(raw: any): string {
    return String(raw?.ncm ?? raw?.NCM ?? '');
}

export function parseToItems(data: Venda): Item[] {
    return data.itens.map((item): Item => {
        const produto = item.produto;
        let label = produto.nome;
        if (parseFloat(item.valor_unitario) > 0) {
            label += ` R$ ${formatToCurrency(item.valor_unitario)}`;
        }
        const codigoBarras = getCodigoBarras(produto);
        if (codigoBarras) {
            label += ` [${codigoBarras}]`;
        }

        return {
            label,
            value: produto.id,
            id: produto.id,
            empresa_id: produto.empresa_id,
            categoria_id: produto.categoria_id || 0,
            sub_categoria_id: produto.sub_categoria_id,
            padrao_id: produto.padrao_id,
            marca_id: produto.marca_id,
            fabricante: produto.fabricante,
            variacao_modelo_id: produto.variacao_modelo_id,
            nome: produto.nome,
            codigo_barras: codigoBarras,
            codigo_barras2: produto.codigo_barras2,
            codigo_barras3: produto.codigo_barras3,
            referencia: produto.referencia,
            ncm: getNcm(produto),
            unidade: getUnidade(produto),
            imagem: produto.imagem,
            perc_icms: produto.perc_icms,
            perc_pis: produto.perc_pis,
            perc_cofins: produto.perc_cofins,
            perc_ipi: produto.perc_ipi,
            cest: produto.cest,
            origem: produto.origem,
            cst_csosn: produto.cst_csosn,
            cst_pis: produto.cst_pis,
            cst_cofins: produto.cst_cofins,
            cst_ipi: produto.cst_ipi,
            perc_red_bc: produto.perc_red_bc,
            pST: produto.pST,
            valor_unitario: getValorUnitario(item) || getValorUnitario(produto),
            valor_compra: produto.valor_compra,
            percentual_lucro: produto.percentual_lucro,
            cfop_estadual: produto.cfop_estadual,
            cfop_outro_estado: produto.cfop_outro_estado,
            cfop_entrada_estadual: produto.cfop_entrada_estadual,
            cfop_entrada_outro_estado: produto.cfop_entrada_outro_estado,
            codigo_beneficio_fiscal: produto.codigo_beneficio_fiscal,
            cEnq: produto.cEnq,
            gerenciar_estoque: produto.gerenciar_estoque,
            adRemICMSRet: produto.adRemICMSRet,
            pBio: produto.pBio,
            tipo_servico: produto.tipo_servico,
            indImport: produto.indImport,
            cUFOrig: produto.cUFOrig,
            pOrig: produto.pOrig,
            codigo_anp: produto.codigo_anp,
            perc_glp: produto.perc_glp,
            perc_gnn: produto.perc_gnn,
            perc_gni: produto.perc_gni,
            valor_partida: produto.valor_partida,
            unidade_tributavel: produto.unidade_tributavel,
            quantidade_tributavel: produto.quantidade_tributavel,
            status: produto.status,
            cardapio: produto.cardapio,
            delivery: produto.delivery,
            reserva: produto.reserva,
            ecommerce: produto.ecommerce,
            nome_en: produto.nome_en,
            nome_es: produto.nome_es,
            descricao: produto.descricao,
            descricao_en: produto.descricao_en,
            descricao_es: produto.descricao_es,
            valor_cardapio: produto.valor_cardapio ?? '',
            valor_delivery: produto.valor_delivery ?? '',
            destaque_delivery: produto.destaque_delivery,
            oferta_delivery: produto.oferta_delivery,
            tempo_preparo: produto.tempo_preparo,
            tipo_carne: produto.tipo_carne,
            tipo_unico: produto.tipo_unico,
            composto: produto.composto,
            combo: produto.combo,
            margem_combo: produto.margem_combo,
            estoque_minimo: produto.estoque_minimo,
            alerta_validade: produto.alerta_validade,
            referencia_balanca: produto.referencia_balanca,
            balanca_pdv: produto.balanca_pdv,
            valor_ecommerce: produto.valor_ecommerce,
            destaque_ecommerce: produto.destaque_ecommerce,
            percentual_desconto: produto.percentual_desconto,
            descricao_ecommerce: produto.descricao_ecommerce,
            texto_ecommerce: produto.texto_ecommerce,
            largura: produto.largura ? String(produto.largura) : null,
            comprimento: produto.comprimento ? String(produto.comprimento) : null,
            altura: produto.altura ? String(produto.altura) : null,
            peso: produto.peso ? String(produto.peso) : null,
            hash_ecommerce: produto.hash_ecommerce,
            hash_delivery: produto.hash_delivery || '',
            texto_delivery: produto.texto_delivery,
            mercado_livre_id: produto.mercado_livre_id,
            mercado_livre_link: produto.mercado_livre_link,
            mercado_livre_valor: produto.mercado_livre_valor,
            mercado_livre_categoria: produto.mercado_livre_categoria,
            condicao_mercado_livre: produto.condicao_mercado_livre,
            quantidade_mercado_livre: produto.quantidade_mercado_livre,
            mercado_livre_tipo_publicacao: produto.mercado_livre_tipo_publicacao,
            mercado_livre_youtube: produto.mercado_livre_youtube,
            mercado_livre_descricao: produto.mercado_livre_descricao,
            mercado_livre_status: produto.mercado_livre_status,
            woocommerce_id: produto.woocommerce_id ? String(produto.woocommerce_id) : null,
            woocommerce_slug: produto.woocommerce_slug,
            woocommerce_link: produto.woocommerce_link,
            woocommerce_valor: produto.woocommerce_valor,
            woocommerce_type: produto.woocommerce_type,
            woocommerce_status: produto.woocommerce_status,
            woocommerce_descricao: produto.woocommerce_descricao,
            woocommerce_stock_status: produto.woocommerce_stock_status,
            categorias_woocommerce: produto.categorias_woocommerce,
            nuvem_shop_id: produto.nuvem_shop_id ? String(produto.nuvem_shop_id) : null,
            nuvem_shop_valor: produto.nuvem_shop_valor,
            texto_nuvem_shop: produto.texto_nuvem_shop,
            modBCST: produto.modBCST,
            pMVAST: produto.pMVAST,
            pICMSST: produto.pICMSST,
            redBCST: produto.redBCST,
            valor_atacado: produto.valor_atacado,
            quantidade_atacado: produto.quantidade_atacado ? String(produto.quantidade_atacado) : null,
            created_at: produto.created_at,
            updated_at: produto.updated_at,
            ponto_carne: produto.ponto_carne,
            codigo: produto.codigo ?? '',
            estoque_atual: 0,
            imgApp: produto.imgApp,
            qtd: parseFloat(item.quantidade),
            vl_total: parseFloat(item.sub_total),
        };
    });
}

export function parseItem(data: ProdutoResponse): Item {
    const valorUnitario = getValorUnitario(data);
    let label = data.nome;
    if (parseFloat(valorUnitario) > 0) {
        label += ` R$ ${formatToCurrency(valorUnitario)}`;
    }
    if (data.codigo_barras) {
        label += ` [${data.codigo_barras}]`;
    }
    return {
        id: data.id,
        value: data.id,
        label,
        empresa_id: data.empresa_id,
        categoria_id: data.categoria_id || 0,
        sub_categoria_id: data.sub_categoria_id,
        padrao_id: data.padrao_id || null,
        marca_id: data.marca_id || null,
        fabricante: data.fabricante || null,
        variacao_modelo_id: data.variacao_modelo_id || null,
        nome: data.nome,
        codigo_barras: (data as any).codigo_barras || getCodigoBarras(data),
        codigo_barras2: data.codigo_barras2 || null,
        codigo_barras3: data.codigo_barras3 || null,
        referencia: data.referencia || null,
        ncm: getNcm(data),
        unidade: getUnidade(data),
        imagem: String(data.imgApp || ''),
        perc_icms: data.perc_icms,
        perc_pis: data.perc_pis,
        perc_cofins: data.perc_cofins,
        perc_ipi: data.perc_ipi,
        cest: data.cest || null,
        origem: data.origem,
        cst_csosn: data.cst_csosn,
        cst_pis: data.cst_pis,
        cst_cofins: data.cst_cofins,
        cst_ipi: data.cst_ipi,
        perc_red_bc: data.perc_red_bc || null,
        pST: data.pST || null,
        valor_unitario: valorUnitario,
        valor_compra: data.valor_compra,
        percentual_lucro: data.percentual_lucro,
        cfop_estadual: data.cfop_estadual,
        cfop_outro_estado: data.cfop_outro_estado,
        cfop_entrada_estadual: data.cfop_entrada_estadual,
        cfop_entrada_outro_estado: data.cfop_entrada_outro_estado,
        codigo_beneficio_fiscal: data.codigo_beneficio_fiscal || null,
        cEnq: data.cEnq,
        gerenciar_estoque: data.gerenciar_estoque,
        adRemICMSRet: data.adRemICMSRet,
        pBio: data.pBio,
        tipo_servico: data.tipo_servico,
        indImport: data.indImport,
        cUFOrig: data.cUFOrig || '',
        pOrig: data.pOrig,
        codigo_anp: data.codigo_anp || '',
        perc_glp: data.perc_glp,
        perc_gnn: data.perc_gnn,
        perc_gni: data.perc_gni,
        valor_partida: data.valor_partida,
        unidade_tributavel: data.unidade_tributavel,
        quantidade_tributavel: data.quantidade_tributavel,
        status: data.status,
        cardapio: data.cardapio,
        delivery: data.delivery,
        reserva: data.reserva,
        ecommerce: data.ecommerce,
        nome_en: data.nome_en || null,
        nome_es: data.nome_es || null,
        descricao: data.descricao || null,
        descricao_en: data.descricao_en || null,
        descricao_es: data.descricao_es || null,
        valor_cardapio: data.valor_cardapio || '',
        valor_delivery: data.valor_delivery || '',
        destaque_delivery: data.destaque_delivery ? 1 : 0,
        oferta_delivery: data.oferta_delivery ? 1 : 0,
        tempo_preparo: data.tempo_preparo || null,
        tipo_carne: data.tipo_carne,
        tipo_unico: data.tipo_unico,
        composto: data.composto,
        combo: data.combo,
        margem_combo: data.margem_combo,
        estoque_minimo: data.estoque_minimo,
        alerta_validade: data.alerta_validade || null,
        referencia_balanca: data.referencia_balanca || null,
        balanca_pdv: data.balanca_pdv,
        valor_ecommerce: data.valor_ecommerce || null,
        destaque_ecommerce: data.destaque_ecommerce || 0,
        percentual_desconto: data.percentual_desconto || null,
        descricao_ecommerce: data.descricao_ecommerce || null,
        texto_ecommerce: data.texto_ecommerce,
        largura: data.largura || null,
        comprimento: data.comprimento || null,
        altura: data.altura || null,
        peso: data.peso || null,
        hash_ecommerce: data.hash_ecommerce || null,
        hash_delivery: data.hash_delivery || '',
        texto_delivery: data.texto_delivery || '',
        mercado_livre_id: data.mercado_livre_id || null,
        mercado_livre_link: data.mercado_livre_link || null,
        mercado_livre_valor: data.mercado_livre_valor || '',
        mercado_livre_categoria: data.mercado_livre_categoria || null,
        condicao_mercado_livre: data.condicao_mercado_livre || null,
        quantidade_mercado_livre: data.quantidade_mercado_livre || null,
        mercado_livre_tipo_publicacao: data.mercado_livre_tipo_publicacao || null,
        mercado_livre_youtube: data.mercado_livre_youtube || null,
        mercado_livre_descricao: data.mercado_livre_descricao || '',
        mercado_livre_status: data.mercado_livre_status || '',
        woocommerce_id: data.woocommerce_id || null,
        woocommerce_slug: data.woocommerce_slug || null,
        woocommerce_link: data.woocommerce_link || null,
        woocommerce_valor: data.woocommerce_valor || null,
        woocommerce_type: data.woocommerce_type || null,
        woocommerce_status: String(data.woocommerce_status || ''),
        woocommerce_descricao: data.woocommerce_descricao || '',
        woocommerce_stock_status: String(data.woocommerce_stock_status || ''),
        categorias_woocommerce: data.categorias_woocommerce || '',
        nuvem_shop_id: data.nuvem_shop_id || null,
        nuvem_shop_valor: data.nuvem_shop_valor || null,
        texto_nuvem_shop: data.texto_nuvem_shop || '',
        modBCST: data.modBCST,
        pMVAST: data.pMVAST || null,
        pICMSST: data.pICMSST || null,
        redBCST: data.redBCST || null,
        valor_atacado: data.valor_atacado,
        quantidade_atacado: data.quantidade_atacado || null,
        created_at: data.created_at,
        updated_at: data.updated_at,
        ponto_carne: data.ponto_carne || null,
        codigo: data.codigo || '',
        estoque_atual: parseFloat(data.estoque?.quantidade) || 0,
        imgApp: String(data.imgApp || ''),
        qtd: data?.quantidade || 1,
        vl_total: parseFloat(valorUnitario),
    };
}
