import { Cliente } from "./company";
export type Item = {
    value: number;
    label: string;
    id: number;
    qtd?: number;
    vl_total?: number;
    empresa_id: number;
    categoria_id: number;
    sub_categoria_id: number | null;
    padrao_id: number | null;
    marca_id: number | null;
    fabricante: string | null;
    variacao_modelo_id: number | null;
    nome: string;
    codigo_barras: string | null;
    codigo_barras2: string | null;
    codigo_barras3: string | null;
    referencia: string | null;
    ncm: string;
    unidade: string;
    imagem: string;
    perc_icms: string;
    perc_pis: string;
    perc_cofins: string;
    perc_ipi: string;
    cest: string | null;
    origem: number;
    cst_csosn: string;
    cst_pis: string;
    cst_cofins: string;
    cst_ipi: string;
    perc_red_bc: string | null;
    pST: string | null;
    valor_unitario: string;
    /** Alguns endpoints do sistema retornam `valor_venda` ao invés de `valor_unitario`. */
    valor_venda?: string;
    valor_compra: string;
    percentual_lucro: string;
    cfop_estadual: string;
    cfop_outro_estado: string;
    cfop_entrada_estadual: string;
    cfop_entrada_outro_estado: string;
    codigo_beneficio_fiscal: string | null;
    cEnq: string;
    gerenciar_estoque: number;
    adRemICMSRet: string;
    pBio: string;
    tipo_servico: number;
    indImport: number;
    cUFOrig: string;
    pOrig: string;
    codigo_anp: string;
    perc_glp: string;
    perc_gnn: string;
    perc_gni: string;
    valor_partida: string;
    unidade_tributavel: string;
    quantidade_tributavel: string;
    status: number;
    cardapio: number;
    delivery: number;
    reserva: number;
    ecommerce: number;
    nome_en: string | null;
    nome_es: string | null;
    descricao: string | null;
    descricao_en: string | null;
    descricao_es: string | null;
    valor_cardapio: string;
    valor_delivery: string;
    destaque_delivery: number;
    oferta_delivery: number;
    tempo_preparo: string | null;
    tipo_carne: number;
    tipo_unico: number;
    composto: number;
    combo: number;
    margem_combo: string;
    estoque_minimo: string;
    alerta_validade: string | null;
    referencia_balanca: string | null;
    balanca_pdv: number;
    valor_ecommerce: string | null;
    destaque_ecommerce: number;
    percentual_desconto: string | null;
    descricao_ecommerce: string | null;
    texto_ecommerce: string;
    largura: string | null;
    comprimento: string | null;
    altura: string | null;
    peso: string | null;
    hash_ecommerce: string | null;
    hash_delivery: string;
    texto_delivery: string;
    mercado_livre_id: string | null;
    mercado_livre_link: string | null;
    mercado_livre_valor: string;
    mercado_livre_categoria: string | null;
    condicao_mercado_livre: string | null;
    quantidade_mercado_livre: string | null;
    mercado_livre_tipo_publicacao: string | null;
    mercado_livre_youtube: string | null;
    mercado_livre_descricao: string;
    mercado_livre_status: string;
    woocommerce_id: string | null;
    woocommerce_slug: string | null;
    woocommerce_link: string | null;
    woocommerce_valor: string | null;
    woocommerce_type: string | null;
    woocommerce_status: string;
    woocommerce_descricao: string;
    woocommerce_stock_status: string;
    categorias_woocommerce: string;
    nuvem_shop_id: string | null;
    nuvem_shop_valor: string | null;
    texto_nuvem_shop: string;
    modBCST: number;
    pMVAST: string | null;
    pICMSST: string | null;
    redBCST: string | null;
    is_atacado?: boolean;
    valor_atacado: string;
    quantidade_atacado: string | null;
    created_at: string;
    updated_at: string;
    ponto_carne: string | null;
    codigo: string;
    estoque_atual: number;
    imgApp: string;
};
export interface Produto {
    id: number;
    empresa_id: number;
    categoria_id: number | null;
    sub_categoria_id: number | null;
    padrao_id: number | null;
    marca_id: number | null;
    fabricante: string | null;
    variacao_modelo_id: number | null;
    nome: string;
    codigo_barras: string | null;
    codigo_barras2: string | null;
    codigo_barras3: string | null;
    referencia: string | null;
    ncm: string;
    unidade: string;
    imagem: string;
    perc_icms: string;
    perc_pis: string;
    perc_cofins: string;
    perc_ipi: string;
    cest: string | null;
    origem: number;
    cst_csosn: string;
    cst_pis: string;
    cst_cofins: string;
    cst_ipi: string;
    perc_red_bc: string | null;
    pST: string | null;
    valor_unitario: string;
    /** Alguns endpoints do sistema retornam `valor_venda` ao invés de `valor_unitario`. */
    valor_venda?: string;
    valor_compra: string;
    percentual_lucro: string;
    cfop_estadual: string;
    cfop_outro_estado: string;
    cfop_entrada_estadual: string;
    cfop_entrada_outro_estado: string;
    codigo_beneficio_fiscal: string | null;
    cEnq: string;
    gerenciar_estoque: number;
    adRemICMSRet: string;
    pBio: string;
    tipo_servico: number;
    indImport: number;
    cUFOrig: string;
    pOrig: string;
    codigo_anp: string;
    perc_glp: string;
    perc_gnn: string;
    perc_gni: string;
    valor_partida: string;
    unidade_tributavel: string;
    quantidade_tributavel: string;
    status: number;
    cardapio: number;
    delivery: number;
    reserva: number;
    ecommerce: number;
    nome_en: string | null;
    nome_es: string | null;
    descricao: string | null;
    descricao_en: string | null;
    descricao_es: string | null;
    valor_cardapio: string | null;
    valor_delivery: string | null;
    destaque_delivery: number;
    oferta_delivery: number;
    tempo_preparo: string | null;
    tipo_carne: number;
    tipo_unico: number;
    composto: number;
    combo: number;
    margem_combo: string;
    estoque_minimo: string;
    alerta_validade: string | null;
    referencia_balanca: string | null;
    balanca_pdv: number;
    valor_ecommerce: string | null;
    destaque_ecommerce: number;
    percentual_desconto: string | null;
    descricao_ecommerce: string | null;
    texto_ecommerce: string;
    largura: number | null;
    comprimento: number | null;
    altura: number | null;
    peso: number | null;
    hash_ecommerce: string | null;
    hash_delivery: string | null;
    texto_delivery: string;
    mercado_livre_id: string | null;
    mercado_livre_link: string | null;
    mercado_livre_valor: string;
    mercado_livre_categoria: string | null;
    condicao_mercado_livre: string | null;
    quantidade_mercado_livre: string | null;
    mercado_livre_tipo_publicacao: string | null;
    mercado_livre_youtube: string | null;
    mercado_livre_descricao: string;
    mercado_livre_status: string;
    woocommerce_id: number | null;
    woocommerce_slug: string | null;
    woocommerce_link: string | null;
    woocommerce_valor: string | null;
    woocommerce_type: string | null;
    woocommerce_status: string;
    woocommerce_descricao: string;
    woocommerce_stock_status: string;
    categorias_woocommerce: string;
    nuvem_shop_id: number | null;
    nuvem_shop_valor: string | null;
    texto_nuvem_shop: string;
    modBCST: number;
    pMVAST: string | null;
    pICMSST: string | null;
    redBCST: string | null;
    valor_atacado: string;
    quantidade_atacado: number | null;
    created_at: string;
    updated_at: string;
    ponto_carne: string | null;
    codigo: string | null;
    imgApp: string;
}
export interface VendaItem {
    id: number;
    venda_id: number;
    produto_id: number;
    variacao_id: number | null;
    quantidade: string; // "1.000"
    valor_unitario: string; // "7500.00"
    sub_total: string; // "7500.00"
    created_at: string;
    updated_at: string;
    produto: Produto;
}
export interface Venda {
    id: number;
    empresa_id: number;
    cliente_id: number;
    total: string;
    desconto: string;
    acrescimo: string;
    observacao: string | null;
    tipo_pagamento: string;
    local_id: number;
    user_id: number;
    funcionario_id: number | null;
    created_at: string;
    updated_at: string;
    itens: VendaItem[];
    cliente?: Cliente;
}
export interface EstoqueResponse {
    id: number;
    produto_id: number;
    produto_variacao_id: number | null;
    quantidade: string;
    local_id: number;
    created_at: string;
    updated_at: string;
}
export interface ProdutoResponse {
    id: number;
    empresa_id: number;
    categoria_id: number | null;
    sub_categoria_id: number | null;
    padrao_id: number | null;
    marca_id: number | null;
    fabricante: string | null;
    variacao_modelo_id: number | null;
    nome: string;
    codigo_barras: string | null;
    codigo_barras2: string | null;
    codigo_barras3: string | null;
    referencia: string | null;
    ncm: string;
    unidade: string;
    imagem: string | null;
    perc_icms: string;
    perc_pis: string;
    perc_cofins: string;
    perc_ipi: string;
    cest: string | null;
    origem: number;
    cst_csosn: string;
    cst_pis: string;
    cst_cofins: string;
    cst_ipi: string;
    perc_red_bc: string | null;
    pST: string | null;
    valor_unitario: string;
    /** Alguns endpoints do sistema retornam `valor_venda` ao invés de `valor_unitario`. */
    valor_venda?: string;
    valor_compra: string;
    percentual_lucro: string;
    cfop_estadual: string;
    cfop_outro_estado: string;
    cfop_entrada_estadual: string;
    cfop_entrada_outro_estado: string;
    codigo_beneficio_fiscal: string | null;
    cEnq: string;
    gerenciar_estoque: number;
    adRemICMSRet: string;
    pBio: string;
    tipo_servico: number;
    indImport: number;
    cUFOrig: string | null;
    pOrig: string;
    codigo_anp: string | null;
    perc_glp: string;
    perc_gnn: string;
    perc_gni: string;
    valor_partida: string;
    unidade_tributavel: string;
    quantidade_tributavel: string;
    status: number;
    cardapio: number;
    delivery: number;
    reserva: number;
    ecommerce: number;
    nome_en: string | null;
    nome_es: string | null;
    descricao: string | null;
    descricao_en: string | null;
    descricao_es: string | null;
    valor_cardapio: string | null;
    valor_delivery: string | null;
    destaque_delivery: number | null;
    oferta_delivery: number | null;
    tempo_preparo: string | null;
    tipo_carne: number;
    tipo_unico: number;
    composto: number;
    combo: number;
    margem_combo: string;
    estoque_minimo: string;
    alerta_validade: string | null;
    referencia_balanca: string | null;
    balanca_pdv: number;
    valor_ecommerce: string | null;
    destaque_ecommerce: number | null;
    percentual_desconto: string | null;
    descricao_ecommerce: string | null;
    texto_ecommerce: string;
    largura: string | null;
    comprimento: string | null;
    altura: string | null;
    peso: string | null;
    hash_ecommerce: string | null;
    hash_delivery: string | null;
    texto_delivery: string;
    mercado_livre_id: string | null;
    mercado_livre_link: string | null;
    mercado_livre_valor: string | null;
    mercado_livre_categoria: string | null;
    condicao_mercado_livre: string | null;
    quantidade_mercado_livre: string | null;
    mercado_livre_tipo_publicacao: string | null;
    mercado_livre_youtube: string | null;
    mercado_livre_descricao: string;
    mercado_livre_status: string;
    woocommerce_id: string | null;
    woocommerce_slug: string | null;
    woocommerce_link: string | null;
    woocommerce_valor: string | null;
    woocommerce_type: string | null;
    woocommerce_status: string | null;
    woocommerce_descricao: string;
    woocommerce_stock_status: string | null;
    categorias_woocommerce: string;
    nuvem_shop_id: string | null;
    nuvem_shop_valor: string | null;
    texto_nuvem_shop: string;
    modBCST: number;
    pMVAST: string | null;
    pICMSST: string | null;
    redBCST: string | null;
    valor_atacado: string;
    quantidade_atacado: string | null;
    created_at: string;
    updated_at: string;
    ponto_carne: string | null;
    codigo: string | null;
    imgApp: string | null;
    estoque_atual: string;
    estoque: EstoqueResponse;
    combinacoes?: string;
    variacoes: Variacao[];
    quantidade?: number;
}
export interface Tamanho {
    id: number;
    empresa_id: number;
    nome: string;
    descricao: string;
    created_at: string;
    updated_at: string;
}

export interface Cor {
    id: number;
    empresa_id: number;
    nome: string;
    codigo: string;
    descricao: string;
    created_at: string;
    updated_at: string;
}

export interface Variacao {
    id: number;
    produto_id: number;
    tamanho_id: number | null;
    cor_id: number | null;
    estoque: number;
    codigo: string;
    imagem_url: string | null;
    created_at: string;
    updated_at: string;
    tamanho?: Tamanho;
    cor?: Cor;
}
